#!/bin/bash

# Custom CLI to run development scripts
case "$1" in
  setup)
    ./scripts/setup.sh
    ;;
  checkdate)
    ./scripts/checkdate.sh
    ;;
  changedate)
    ./scripts/changedate.sh
    ;;
  404)
    cp index.html 404.html
    ;;
  *)
    echo "Usage: $0 {setup|checkdate|changedate|404}"
    exit 1
    ;;
esac
